; LoRa Node Firmware - Generic template
[env:node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_extra_dirs = ../shared

build_flags =
    -DLORA_ADDRESS=5
    ; Override at build time: pio run -t upload -- -DLORA_ADDRESS=10

lib_deps =
    bblanchon/ArduinoJson@^7.0
